# @plugin DuoAuth
# @version 1.1.12
# @author foncused

# Are you using BungeeCord?
# If set to true, DuoAuth.jar should also be installed as a BungeeCord plugin
# This is only useful for blocking proxy-level commands (/server <server>, /send <player> <server>)
bungeecord: false

# The cost factor of the bcrypt algorithm
# For best security measures, it is recommended to set this value in respect to the maximum amount of
# time you are willing to have your players wait to be authenticated (normally 12-17)
cost-factor: 15

# Command options for /auth command
command:

  # The cooldown time in seconds for using the /auth command (bypassed by 'duoauth.bypass')
  cooldown: 20

  # The maximum number of incorrect authentication attempts before players are locked out (bypassed by 'duoauth.unlimited')
  # Disabled by setting to 0
  attempts: 5

# Password options
# For best security measures, set a min-length of at least 8, both-cases to true,
# numbers to true, special-chars to true, and change default (Password1234#) as
# this default config.yml is public on GitHub; be advised the default password
# WILL NOT WORK if it does not meet the other requirements
password:

  # The default password to be used when players join with permission 'duoauth.enforced'
  default: "Password1234#"

  # The minimum length of a provided password
  min-length: 8

  # true to enforce at least one uppercase (A-Z) and one lowercase letter (a-z), false if not
  both-cases: true

  # true to enforce at least one number (0-9), false if not
  numbers: true

  # true to enforce at least one special character in the provided 'special-charset', false if not
  special-chars: true
  special-charset: "@#$%^&+="

# Code options
code:

  # The issuer of the OTP URL
  # This will be the title displayed next to the 2FA code in the mobile authentication app
  issuer: "DuoAuth"

# Deauthentication options
# For best security measures, set ip-changes to true
deauth:

  # true to immediately deauthenticate players whenever their IP addresses change, false if not
  ip-changes: true

  # The time in hours to deauthenticate players after the last successful authentication
  timeout: 72

  # true to deauthenticate players even if they are online (can be annoying), false if not
  timeout-online: false

  # The heartbeat in minutes to check if players should be deauthenticated
  timeout-check-heartbeat: 10

# Unlock options
unlock:

  # The time in hours to automatically unlock locked players
  # Disabled by setting to 0
  timeout: 120

  # The heartbeat in minutes to check if players should be unlocked
  timeout-check-heartbeat: 15

# Database
# The method used for storing the digests
# This is not currently configurable; for now, DuoAuth will only store data in .json files in the /data directory
database: "json"

# true to allow chat prior to authentication, false if not
chat: false

# true to restrict yaw and pitch prior to authentication, false if not
restrict-movement: false
