name: DuoAuth
main: me.foncused.duoauth.DuoAuth
version: 1.1.5
author: foncused
load: STARTUP

commands:
  auth:
    usage: /<command>
    aliases: [2fa]
    description: Authenticate with password and code combo

permissions:
  duoauth.auth:
    default: false
  duoauth.bypass:
    default: false
  duoauth.admin:
    default: false
  duoauth.notify:
    default: false
  duoauth.enforced:
    default: false
  duoauth.unlimited:
    default: false
